#!/usr/bin/python

from twilio.rest import TwilioRestClient
import sys

if len(sys.argv) < 2:
    print "Failure"
    sys.exit()
else:
    number = sys.argv[1]

account_sid = "ACbd5ec998bc884fa1b18c9f146644c91c"
auth_token = "e81f3f4a6175c5be5d754ade48344c39"
client = TwilioRestClient(account_sid, auth_token)
twilio_number = "+12282060032"

message = "Thanks for subscribing to Cat Facts! How much do you know about cats? Probably not enough."
send_message = client.sms.messages.create(to=number[0], from_=twilio_number, body=message)
print "Success"

